FROM ghcr.io/mythicc2profiles/basic_logger:v0.0.1
#FROM golang:1.21 as builder

#WORKDIR /Mythic/

#COPY [".", "."]

#RUN make build

#FROM alpine

#RUN apk add --update make

#COPY --from=0 /main /main

#WORKDIR /Mythic/

#CMD make run